changelog:
  exclude:
    labels:
      - exclude from release notes
  categories:
    - title: New Features
      labels:
        - feature
    - title: Improvements
      labels:
        - improvement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other
      labels:
        - "*"
